trigger:
  branches:
    include:
    - main  # Only run on changes to main
pr:
  branches:
    exclude:
    - '*' # Don't ever run when a PR is created

variables:
- group: AzureML-Bicep-Deploy
- name: agentImageName
  value: ubuntu-latest
- name: workingDirectory
  value: $(System.DefaultWorkingDirectory)/infrastructure

stages:
- stage: Development
  displayName: Deploy Infrastructure
  variables:
  - group: AzureML-Bicep-Deploy-Development
  jobs:
  - job: DeployInfra
    displayName: Deploy Bicep template
    environment: aml-bicep-development
    pool:
      vmImage: $(agentImageName)
    
    steps:
    - template: templates/deploy-template.yaml

- stage: Production
  displayName: Deploy Infrastructure
  variables:
  - group: AzureML-Bicep-Deploy-Production
  jobs:
  - job: DeployInfra
    displayName: Deploy Bicep template
    environment: aml-bicep-production
    pool:
      vmImage: $(agentImageName)
    
    steps:
    - template: templates/deploy-template.yaml

