trigger:
  branches:
    include:
    - main  # Only run on changes to main
pr:
  branches:
    exclude:
    - '*' # Don't ever run when a PR is created

variables:
- name: workingDirectory
  value: $(System.DefaultWorkingDirectory)/infrastructure

stages:
- template: templates/deploy-template.yaml
  variables:
  - group: AzureML-Bicep-Deploy-Development
  parameters:
    serviceConnection: ${{ variables.serviceConnection }}
    stageName: Deploy-Development
    environment: aml-bicep-development
    resourceGroupName: ${{ variables.resourceGroupName }}
    workingDirectory: ${{ variables.workingDirectory }}
    appInsightsName: ${{ variables.appInsightsName }}
    computeInstanceName: ${{ variables.computeInstanceName }}
    computeInstanceSku: ${{ variables.computeInstanceSku }}
    containerRegistryName: ${{ variables.containerRegistryName }}
    createMlCluster: ${{ variables.createMlCluster }}
    createMlComputeInstance: ${{ variables.createMlComputeInstance }}
    keyVaultAccessPolicyTargetObjectId: ${{ variables.keyVaultAccessPolicyTargetObjectId }}
    keyVaultName: ${{ variables.keyVaultName }}
    mlClusterMaxNodeCount: ${{ variables.mlClusterMaxNodeCount }}
    mlClusterMinNodeCount: ${{ variables.mlClusterMinNodeCount }}
    mlClusterName: ${{ variables.mlClusterName }}
    mlClusterSku: ${{ variables.mlClusterSku }}
    mlComputeAssignedUser: ${{ variables.mlComputeAssignedUser }}
    mlWorkspaceName: ${{ variables.mlWorkspaceName }}
    storageAccountName: ${{ variables.storageAccountName }}
