trigger:
  branches:
    include:
    - main  # Only run on changes to main
pr:
  branches:
    exclude:
    - '*' # Don't ever run when a PR is created

variables:
- name: agentImageName
  value: ubuntu-latest
- name: workingDirectory
  value: $(System.DefaultWorkingDirectory)/infrastructure

stages:
- stage: DeployDevelopment
  displayName: Deploy to Development
  variables:
  - group: AzureML-Bicep-Deploy-Development
  jobs:
  - template: templates/deploy-template.yaml
    parameters:
      environment: aml-bicep-development

- stage: DeployProduction
  displayName: Deploy to Production
  variables:
  - group: AzureML-Bicep-Deploy-Production
  jobs:
  - template: templates/deploy-template.yaml
    parameters:
      environment: aml-bicep-Production

# - stage: Development
#   displayName: Deploy Infrastructure
#   variables:
#   - group: AzureML-Bicep-Deploy-Development
#   jobs:
#   - job: DeployInfra
#     displayName: Deploy Bicep template
#     pool:
#       vmImage: $(agentImageName)
    
#     steps:
#     - template: templates/deploy-template.yaml

# - stage: Production
#   displayName: Deploy Infrastructure
#   variables:
#   - group: AzureML-Bicep-Deploy-Production
#   jobs:
#   - job: DeployInfra
#     displayName: Deploy Bicep template
#     pool:
#       vmImage: $(agentImageName)
    
#     steps:
#     - template: templates/deploy-template.yaml
