trigger:
  branches:
    include:
    - main
pr:
  branches:
    exclude:
    - '*'

variables:
- group: AzureML-Bicep-Deploy
- name: agentImageName
  value: ubuntu-latest
- name: workingDirectory
  value: $(System.DefaultWorkingDirectory)/infrastructure

stages:
- stage: Deploy
  displayName: Deploy Infrastructure
  
  jobs:
  - job: DeployInfra
    displayName: Deploy Bicep template
    pool:
      vmImage: $(agentImageName)
    
    steps:
    - task: AzureCLI@2
      displayName: 'az group deployment create'
      inputs:
       azureSubscription: $(serviceConnection)
       scriptType: bash
       scriptLocation: inlineScript
       inlineScript: |
         DEPLOYMENT_NAME="aml-infra-deploy-$(date '+%F_%H_%M_%S')"
         echo "Using deployment name $DEPLOYMENT_NAME"
         az deployment group create -g "$(resourceGroupName)" -n "$DEPLOYMENT_NAME" --template-file "$(workingDirectory)/azureml.bicep" --parameters appInsightsName=$(appInsightsName) computeInstanceName=$(computeInstanceName) computeInstanceSku=$(computeInstanceSku) containerRegistryName=$(containerRegistryName) createMlCluster=$(createMlCluster) createMlComputeInstance=$(createMlComputeInstance) keyVaultAccessPolicyTargetObjectId=$(keyVaultAccessPolicyTargetObjectId) keyVaultName=$(keyVaultName) mlClusterMaxNodeCount=$(mlClusterMaxNodeCount) mlClusterMinNodeCount=$(mlClusterMinNodeCount) mlClusterName=$(mlClusterName) mlClusterSku=$(mlClusterSku) mlComputeAssignedUser=$(mlComputeAssignedUser) mlWorkspaceName=$(mlWorkspaceName) storageAccountName=$(storageAccountName)
